//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionService
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Poll_Option
    {
        public long Id { get; set; }
        public long PollId { get; set; }
        public long OptionId { get; set; }
        public int Votes { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        public virtual PollOption PollOption { get; set; }
        public virtual Poll Poll { get; set; }
    }
}
