//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionService
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_User_Chat
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long ChatId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifedDateTime { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
