//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interaction_BinaryObject
    {
        public long Id { get; set; }
        public Nullable<long> ChatId { get; set; }
        public Nullable<long> MessageId { get; set; }
        public Nullable<long> TaskId { get; set; }
        public Nullable<long> PollId { get; set; }
        public Nullable<long> VoteId { get; set; }
        public long BinaryId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        public virtual BinaryObject BinaryObject { get; set; }
        public virtual Chat Chat { get; set; }
        public virtual Message Message { get; set; }
        public virtual Poll Poll { get; set; }
        public virtual Task Task { get; set; }
        public virtual C_User_Poll_Option C_User_Poll_Option { get; set; }
    }
}
