//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoCapEntities : DbContext
    {
        public MoCapEntities()
            : base("name=MoCapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Poll_Option> C_Poll_Option { get; set; }
        public virtual DbSet<C_Task_Task> C_Task_Task { get; set; }
        public virtual DbSet<BinaryObject> BinaryObjects { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Interaction_BinaryObject> Interaction_BinaryObject { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<PollOption> PollOptions { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Timeslouse> Timeslice { get; set; }
        public virtual DbSet<C_User_Chat> C_User_Chat { get; set; }
        public virtual DbSet<C_User_Message> C_User_Message { get; set; }
        public virtual DbSet<C_User_Poll_Option> C_User_Poll_Option { get; set; }
        public virtual DbSet<C_User_Project> C_User_Project { get; set; }
    }
}
