//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            this.Interaction_BinaryObject = new HashSet<Interaction_BinaryObject>();
            this.C_User_Message = new HashSet<C_User_Message>();
        }
    
        public long Id { get; set; }
        public string Label { get; set; }
        public string Text { get; set; }
        public long SenderId { get; set; }
        public bool ReadReceipt { get; set; }
        public int TimeToLive { get; set; }
        public Nullable<System.DateTime> DateTimeOfDeath { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifedDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interaction_BinaryObject> Interaction_BinaryObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_User_Message> C_User_Message { get; set; }
    }
}
