//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractionService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeslouse
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> TaskId { get; set; }
        public Nullable<long> ChatId { get; set; }
        public Nullable<long> PollId { get; set; }
        public long Duration { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
    
        public virtual Chat Chat { get; set; }
        public virtual Poll Poll { get; set; }
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
    }
}
