//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Expense : IExpense
{
	public virtual void AddReceipt(System.Drawing.Image pImage, decimal pValue)
	{
		throw new System.NotImplementedException();
	}

	public Expense()
	{
	}

	public virtual void DeleteReceipt(System.Drawing.Image pImage, decimal pValue)
	{
		throw new System.NotImplementedException();
	}

	public virtual void EditReceipt(System.Drawing.Image pImage, System.Drawing.Image pNewImage, decimal pValue, decimal pNewValue)
	{
		throw new System.NotImplementedException();
	}

}

