//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

public class Expense : IExpense, IInteraction
{
    public string Id
    {
        get
        {
            throw new NotImplementedException();
        }
    }

    public DateTime StartDateTime
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    public DateTime EndDateTime
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    public DateTime CreatedDateTime
    {
        get
        {
            throw new NotImplementedException();
        }
    }

    public DateTime ModifiedDateTime
    {
        get
        {
            throw new NotImplementedException();
        }
    }

    public bool IsActive
    {
        get
        {
            throw new NotImplementedException();
        }
    }

    public string Text
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    public InteractionType Type
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    public IUser Creator
    {
        get
        {
            throw new NotImplementedException();
        }
    }

    public IUser Owner
    {
        get
        {
            throw new NotImplementedException();
        }
    }

    public InteractionState State
    {
        get
        {
            throw new NotImplementedException();
        }
    }

    public decimal Value
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    public Image Receipt
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    public virtual void AddReceipt(Image pImage)
	{
		throw new System.NotImplementedException();
	}

	public virtual void OnComplete(InteractionEventArgs pEventArgs)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeOwner(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeIsActive(bool pActive)
	{
		throw new System.NotImplementedException();
	}

	public Expense()
	{
	}

	public virtual void DeleteReceipt(Image pImage)
	{
		throw new System.NotImplementedException();
	}

	public virtual void EditReceipt(Image pImage)
	{
		throw new System.NotImplementedException();
	}

	public virtual void OnModify(InteractionEventArgs pEventArgs)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeState(InteractionState pState)
	{
		throw new System.NotImplementedException();
	}

	public virtual void OnStateChanged(InteractionEventArgs pEventArgs)
	{
		throw new System.NotImplementedException();
	}

}

