//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Helper
{
	public virtual string GenerateId()
	{
		throw new System.NotImplementedException();
	}

	public virtual int DiffSeconds(DateTime pStartDateTime, DateTime pEndDateTime)
	{
		throw new System.NotImplementedException();
	}

	public virtual int DiffMinutes(DateTime pStartDateTime, DateTime pEndDateTime)
	{
		throw new System.NotImplementedException();
	}

	public virtual int DiffHours(DateTime pStartDateTime, DateTime pEndDateTime)
	{
		throw new System.NotImplementedException();
	}

	public virtual int DiffDays(DateTime pStartDateTime, DateTime pEndDateTime)
	{
		throw new System.NotImplementedException();
	}

	public virtual int CalculateAvailableMinutes(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<ITask> GetTasksByUser(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<ISurvey> GetPendingSurveysByUser(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<IProject> GetProjectsByUser(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

}

