//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IAccount  : ITask
{
	IEnumerable<IExpense> ExpenseList { get;set; }

	IEnumerable<ITimeslice> TimesliceList { get;set; }

	void AddExpense(IExpense pExpense);

	void AddTimeslice(ITimeslice pTimeslice);

	void EditExpense(IExpense pExpense);

	void DeleteExpense(IExpense pExpense);

	void EditTimeslice(ITimeslice PTimeslice);

	void DeleteTimeslice(ITimeslice pTimeslice);

}

