//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IChatMessage 
{
	void Destroy();

	void Forward(List<IUser> pUsers);

	void Reply(string pText, int pTimeToLive, DateTime pActiveDateTime);

}

