//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

public interface IExpense 
{
	decimal Value { get;set; }

	Image Receipt { get;set; }

	void AddReceipt(Image pImage);

}

