//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IHelper 
{
	string GenerateId();

	int DiffSeconds(DateTime pStartDateTime, DateTime pEndDateTime);

	int DiffMinutes(DateTime pStartDateTime, DateTime pEndDateTime);

	int DiffHours(DateTime pStartDateTime, DateTime pEndDateTime);

	int DiffDays(DateTime pStartDateTime, DateTime pEndDateTime);

	int DiffMonths(DateTime pStartDateTime, DateTime pEndDateTime);

	int CalculateAvailableMinutes(IUser pUser);

	List<ITasks> GetTasksByUser(IUser pUser);

	List<ISurvey> GetPendingSurveysByUser(IUser pUser);

	List<IProject> GetProjectsByUser(IUser pUser);

}

