//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IInteractionManager  : ISurveyFactory, IProjectFactory, ITaskFactory, IOutlayFactory, IAccountFactory
{
	List<ISurvey> SurveyList { get;set; }

	List<IProject> ProjectList { get;set; }

	List<ITask> TaskList { get;set; }

	List<Outlay> OutlayList { get;set; }

}

