//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IInteraction 
{
	string Id { get;set; }

	DateTime StartDateTime { get;set; }

	DateTime EndDateTime { get;set; }

	DateTime CreatedDateTime { get;set; }

	DateTime ModifiedDateTime { get;set; }

	bool IsActive { get;set; }

	string Text { get;set; }

	PlexByte.MoCap::PlexByte.MoCap.Interactions::InteractionType Type { get;set; }

	void OnComplete(PlexByte.MoCap::Interactions::IInteraction pInteraction, InteractionEventArgs e);

	void ChangeOwner(IUser pUser);

	void ChangeIsActive(bool pActive);

}

