//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public enum InteractionAttributes : int
{
	CreatedDateTime,
	EndDateTime,
	StartDateTime,
	IsActive,
	Owner,
	State,
	Text,
	Type,
	VoteList,
	OptionList,
	UserList,
	Progress,
	Budget,
	UsedBudget,
	UsedDuration,
	TaskList,
	SurveyList,
	MemberList,
	InvitationList,
	ExpenseList,
	Value,
	TimesliceList,
	Receipt,
}
