//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IOutlayFactory 
{
	ITimeslice CreateTimeslice(string pId, IUser pUser, int pDuration);

	ITimeslice CreateTimeslice(string pId, IUser pUser, DateTime pStartDT, DateTime pEndDT);

	void AddReceipt(IExpense pExpense, System.Drawing.Image pImage);

	IExpense CreateExpense(string pId, string pText, IUser pUser);

	IExpense CreateExpense(string pId, string pText, System.Drawing.Image pReceipt, decimal pValue, IUser pUser);

}

