//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IPollFactory 
{
	IVote CreateVote(IUser pUser, IOption pOption);

	IPollOption CreatePollOption(string pText);

	IPoll CreatePoll(string pText, List<PollOptions> pOptions);

	IPoll CreatePoll(string pText, List<string> pOptions);

}

