//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IProjectFactory 
{
	void AddSurvey(ISurvey pSurvey);

	void AddTask(ITask pTask);

	void Create(string pId, string pText, IUser pCreator);

	void Create(string pId, string pText, IUser pCreatur, bool pEnableBalance, bool pEnableSurvey, List<IUser> pMemberList, List<IUser> pInvitationList);

	void Invite(IUser pUser);

	void Accept(IUser pUser);

}

