//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IProjectFactory 
{
	void AddSurvey(ISurvey pSurvey);

	void AddTask(ITask pTask);

	IProject CreateProject(string pId, string pText, bool pEnableBalance, bool pEnableSurvey, IUser pCreator);

	IProject CreateProject(string pId, string pText, IUser pCreatur, List<string> MemberList, List<string> InvitationList, bool pEnableBalance, bool pEnableSurvey, List<ITask> TaskList, List<ISurvey> SurveyList);

	void Invite(IUser pUser);

	void Accept(IUser pUser);

}

