//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IProject 
{
	bool EnableBalance { get;set; }

	bool EnableSurvey { get;set; }

	List<IUser> InvitationList { get;set; }

	IAccount ProjectAccount { get;set; }

	IEnumerable<ITask> TaskList { get;set; }

	IEnumerable<ISurvey> SurveyList { get;set; }

	IEnumerable<IUser> MemberList { get;set; }

	void AddTask(ITask pTask);

	void AddSurvey(ISurvey pSurvey);

	void Invite(IUser pUser);

	void Accept(IUser pUser);

	void Leave(IUser pUser);

	void KickUser(IUser pUser);

}

