//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IProject 
{
	bool EnableBalance { get;set; }

	bool EnableSurvey { get;set; }

	List<string> MemberList { get;set; }

	List<string> InvitationList { get;set; }

	List<Task> TaskList { get;set; }

	List<Survey> SurveyList { get;set; }

	IAccount IAccount { get;set; }

	void AddTask(ITask pTask);

	void AddSurvey(ISurvey pSurvey);

	void Invite(IUser pUser);

	void Accept(IUser pUser);

	void Leave();

	void KickUser(IUser pUser);

}

