//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface ISurvey 
{
	IEnumerable<ISurveyOption> OptionList { get;set; }

	IEnumerable<IVote> VoteList { get;set; }

	void AddVote(IVote pVote);

	void AddOption(ISurveyOption pOption);

}

