//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface ISurveyFactory 
{
	IVote CreateVote(string pId, IUser pUser, ISurveyOption pOption);

	ISurveyOption CreateSurveyOption(string pId, string pText);

	ISurvey CreateSurvey(string pId, string pText, List<ISurveyOptions> pOptions, IUser pCreator);

	ISurvey CreateSurvey(string pId, string pText, List<string> pOptions, IUser pCreator);

	void AddOption(ISurvey pSurvey, ISurveyOption pOption);

	void AddVote(ISurvey pSurvey, IVote pVote);

}

