//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ObjectFactory : IObjectFactory
{
	public virtual IVote CreateVote(string pId, IUser pUser, ISurveyOption pOption)
	{
		throw new System.NotImplementedException();
	}

	public virtual ITimeslice CreateTimeslice(string pId, IUser pUser, DateTime pStartDT, DateTime pEndDT, IInteraction pTarget)
	{
		throw new System.NotImplementedException();
	}

	public virtual ITimeslice CreateTimeslice(string pId, IUser pUser, int pDuration, IInteraction pTarget)
	{
		throw new System.NotImplementedException();
	}

	public virtual ISurveyOption CreateSurveyOption(string pId, string pText)
	{
		throw new System.NotImplementedException();
	}

	public virtual IExpense CreateExpense(string pId, string pText, System.Drawing.Image pReceipt, decimal pValue, IUser pUser, IInteraction pTarget)
	{
		throw new System.NotImplementedException();
	}

	public virtual IExpense CreateExpense(string pId, string pText, IUser pUser, IInteraction pTarget)
	{
		throw new System.NotImplementedException();
	}

	public ObjectFactory()
	{
	}

}

