//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OutlayFactory : IOutlayFactory
{
	public virtual void CreateTimeslice(string pId, IUser pUser, int pDuration)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CreateTimeslice(string pId, IUser pUser, DateTime pStartDT, DateTime pEndDT)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddReceipt(IExpense pExpense, System.Drawing.Image pImage)
	{
		throw new System.NotImplementedException();
	}

}

