//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PollFactory : IPollFactory
{
	public virtual IVote CreateVote(IUser pUser, IOption pOption)
	{
		throw new System.NotImplementedException();
	}

	public virtual IPollOption CreatePollOption(string pText)
	{
		throw new System.NotImplementedException();
	}

	public virtual IPoll CreatePoll(string pText, List<PollOptions> pOptions)
	{
		throw new System.NotImplementedException();
	}

	public virtual IPoll CreatePoll(string pText, List<string> pOptions)
	{
		throw new System.NotImplementedException();
	}

}

