//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ProjectFactory : IProjectFactory
{
	public virtual void AddSurvey(ISurvey pSurvey)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddTask(ITask pTask)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Create(string pId, string pText, bool pEnableBalance, bool pEnableSurvey, IUser pCreator)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Create(string pId, string pText, IUser pCreatur, List<string> MemberList, List<string> InvitationList, bool pEnableBalance, bool pEnableSurvey, List<ITask> TaskList, List<ISurvey> SurveyList)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Invite(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Accept(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

}

