//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Project : IProject, IInteraction
{
	public virtual void OnComplete(InteractionEventArgs pEventArgs)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeOwner(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeIsActive(bool pActive)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddTask(ITask pTask)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddPoll(IPoll pPoll)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Invite(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Accept(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Leave()
	{
		throw new System.NotImplementedException();
	}

	public virtual void KickUser(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void OnModify(InteractionEventArgs pEventArgs)
	{
		throw new System.NotImplementedException();
	}

}

