//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SurveyFactory : ISurveyFactory
{
	public virtual IVote CreateVote(string pUser, IUser pOption, IOption pOption)
	{
		throw new System.NotImplementedException();
	}

	public virtual ISurveyOption CreateSurveyOption(string pText, string pText)
	{
		throw new System.NotImplementedException();
	}

	public virtual ISurvey CreateSurvey(string pText, string pOptions, List<PollOptions> pCreator, IUser pCreator)
	{
		throw new System.NotImplementedException();
	}

	public virtual ISurvey CreateSurvey(string pText, string pOptions, List<string> pCreator, IUser pCreator)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddOption(ISurvey pSurvey, ISurveyOption pOption)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddVote(ISurvey pSurvey, IVote pVote)
	{
		throw new System.NotImplementedException();
	}

}

