//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Survey : ISurvey, IInteraction
{
    IEnumerable<ISurveyOption> ISurvey.OptionList
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    IEnumerable<IVote> ISurvey.VoteList
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    string IInteraction.Id
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    DateTime IInteraction.StartDateTime
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    DateTime IInteraction.EndDateTime
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    DateTime IInteraction.CreatedDateTime
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    DateTime IInteraction.ModifiedDateTime
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    bool IInteraction.IsActive
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    string IInteraction.Text
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    InteractionType IInteraction.Type
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    InteractionEventArgs IInteraction.InteractionEventArgs
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }

    public virtual void OnComplete(IInteraction pInteraction, InteractionEventArgs e)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeOwner(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeIsActive(bool pActive)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddVote(IVote pOption)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddOption(ISurveyOption pOption)
	{
		throw new System.NotImplementedException();
	}

    void ISurvey.AddVote(IVote pVote)
    {
        throw new NotImplementedException();
    }

    void ISurvey.AddOption(ISurveyOption pOption)
    {
        throw new NotImplementedException();
    }

    void IInteraction.OnComplete(IInteraction pInteraction, InteractionEventArgs e)
    {
        throw new NotImplementedException();
    }

    void IInteraction.ChangeOwner(IUser pUser)
    {
        throw new NotImplementedException();
    }

    void IInteraction.ChangeIsActive(bool pActive)
    {
        throw new NotImplementedException();
    }

    public Survey(string pId, string pText, List<ISurveyOption> pOptions, IUser pCreator)
	{
	}

	public Survey(string pId, string pText, List<string> pOptions, IUser pCreator)
	{
	}

}

