//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SurveyFactory : ISurveyFactory
{
	public virtual IVote CreateVote(string pId, IUser pUser, ISurveyOption pOption)
	{
		throw new System.NotImplementedException();
	}

	public virtual ISurveyOption CreateSurveyOption(string pId, string pText)
	{
		throw new System.NotImplementedException();
	}

	public virtual ISurvey CreateSurvey(string pId, string pText, List<ISurveyOption> pOptions, IUser pCreator)
	{
		throw new System.NotImplementedException();
	}

	public virtual ISurvey CreateSurvey(string pId, string pText, List<string> pOptions, IUser pCreator)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddOption(ISurvey pSurvey, ISurveyOption pOption)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddVote(ISurvey pSurvey, IVote pVote)
	{
		throw new System.NotImplementedException();
	}

    IVote ISurveyFactory.CreateVote(string pId, IUser pUser, ISurveyOption pOption)
    {
        throw new NotImplementedException();
    }

    ISurveyOption ISurveyFactory.CreateSurveyOption(string pId, string pText)
    {
        throw new NotImplementedException();
    }

    ISurvey ISurveyFactory.CreateSurvey(string pId, string pText, List<ISurveyOption> pOptions, IUser pCreator)
    {
        throw new NotImplementedException();
    }

    ISurvey ISurveyFactory.CreateSurvey(string pId, string pText, List<string> pOptions, IUser pCreator)
    {
        throw new NotImplementedException();
    }

    void ISurveyFactory.AddOption(ISurvey pSurvey, ISurveyOption pOption)
    {
        throw new NotImplementedException();
    }

    void ISurveyFactory.AddVote(ISurvey pSurvey, IVote pVote)
    {
        throw new NotImplementedException();
    }
}

