//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Task : IInteraction, ITask
{
	public virtual void OnComplete(InteractionEventArgs pEventArgs)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeOwner(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeIsActive(bool pActive)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddTimeslice(int pTimeslice)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddExpense(decimal pExpense)
	{
		throw new System.NotImplementedException();
	}

	public virtual void OnModify(InteractionEventArgs pEventArgs)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ChangeState(InteractionState pState)
	{
		throw new System.NotImplementedException();
	}

	public virtual void OnStateChanged(InteractionEventArgs pEventArgs)
	{
		throw new System.NotImplementedException();
	}

	private void InitializeProperties()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UdateProgress(int pProgress)
	{
		throw new System.NotImplementedException();
	}

	public Task(string pId, string pText, IUser pCreator)
	{
	}

	public Task(string pId, string pText, IUser pCreator, DateTime pStartDt, DateTime pEndDt, DateTime pDueDt)
	{
	}

	public Task(string pId, string pText, IUser pCreator, DateTime pStartDt, DateTime pEndDt, DateTime pDueDt, decimal pBudget, int pDuration, int pPriority, InteractionState pState, decimal pBudgetUsed, int pTimeUsed, List<ITask> pSubTask, int pProgress)
	{
	}

	public virtual void AddSubTask(ITask pTask)
	{
		throw new System.NotImplementedException();
	}

}

