//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Timeslice : ITimeslice
{
	public Timeslice(string pId, IUser pUser, int pDuration, IInteraction pTarget)
	{
	}

	public Timeslice(string pId, IUser pUser, DateTime pStartDT, DateTime pEndDT, IInteraction pTarget)
	{
	}

	public virtual int CalculateDuration(DateTime pStartDT, DateTime pEndDT)
	{
		throw new System.NotImplementedException();
	}

}

