//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FormManager
{
	public virtual DockContent CreateFormFromObject(IInteraction pObject)
	{
		throw new System.NotImplementedException();
	}

	private DockContent CreateProjectForm(IProject pInstance)
	{
		throw new System.NotImplementedException();
	}

	private DockContent CreateExpenseForm(IExpense pInstance)
	{
		throw new System.NotImplementedException();
	}

	private DockContent CreateSurveyForm(ISurvey pInstance)
	{
		throw new System.NotImplementedException();
	}

	private DockContent CreateTimesliceForm(ITimeslice pInstance)
	{
		throw new System.NotImplementedException();
	}

	private DockContent CreateTaskForm(ITask pInstance)
	{
		throw new System.NotImplementedException();
	}

	public virtual DockContent CreateUserFormFromObject(IUser pInstance)
	{
		throw new System.NotImplementedException();
	}

	public virtual DockContent CreateFormFromObject(IInteraction pObject, DockContent pInstance)
	{
		throw new System.NotImplementedException();
	}

	public virtual T CreateObjectFromForm<T>(DockContent pInstance)
	{
		throw new System.NotImplementedException();
	}

	public virtual IUser CreateUserObjectFromFForm(DockContent pInstance)
	{
		throw new System.NotImplementedException();
	}

}

