//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ObjectManager
{
	public virtual List<IProject> ProjectList
	{
		get;
		private set;
	}

	public virtual List<ITask> TaskList
	{
		get;
		private set;
	}

	public virtual List<ISurvey> SurveyList
	{
		get;
		private set;
	}

	public virtual List<IExpense> ExpenseList
	{
		get;
		private set;
	}

	public virtual List<Timeslice> TimesliceList
	{
		get;
		private set;
	}

	public virtual List<IUser> UserList
	{
		get;
		private set;
	}

	private void GetAllProjectUsers(string pProjectId)
	{
		throw new System.NotImplementedException();
	}

	private void GetAllTasks(string pId, bool pIsProjectId)
	{
		throw new System.NotImplementedException();
	}

	private void GetAllSurveys(string pId, bool pIsProjectId)
	{
		throw new System.NotImplementedException();
	}

	private void GetAllTimeslices(string pId, bool pIsProjectId)
	{
		throw new System.NotImplementedException();
	}

	private void GetAllExpenses(string pId, bool pIsProjectId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void InitializeDBObjects(string pUserId)
	{
		throw new System.NotImplementedException();
	}

	public virtual T GetObjectById<T>(string pId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void LoginUser(string pId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void LogoutUser()
	{
		throw new System.NotImplementedException();
	}

	public virtual T CreateObjectFromForm<T>(DockCOntent pForm)
	{
		throw new System.NotImplementedException();
	}

	public virtual DockContent CreateFormFromObject<T>(T pObject)
	{
		throw new System.NotImplementedException();
	}

}

