//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MoCap.Portable.Library.Interaction
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface Interaction 
	{
		long ID { get;set; }

		DateTime Created { get;set; }

		DateTime Modified { get;set; }

		string Text { get;set; }

		bool IsActive { get;set; }

		DateTime Begin { get;set; }

		DateTime End { get;set; }

		DateTime Due { get;set; }

	}
}

