//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MoCap.Portable.Library.Interaction
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PollOption
	{
		public virtual MoCap.Portable.Library.Interaction.Vote Vote
		{
			get;
			set;
		}

		public virtual Poll Poll
		{
			get;
			set;
		}

	}
}

