//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MoCap.Portable.Library.Interaction
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Task : IInteraction
	{
		public virtual decimal Duration
		{
			get;
			set;
		}

		public virtual decimal Budget
		{
			get;
			set;
		}

		public virtual User Owner
		{
			get;
			set;
		}

		public virtual User Creator
		{
			get;
			set;
		}

		public virtual IEnumerable<Expense> Expense
		{
			get;
			set;
		}

		public virtual IEnumerable<TimeSlice> TimeSlice
		{
			get;
			set;
		}

		public virtual Task Task
		{
			get;
			set;
		}

		public virtual IEnumerable<Task> Task
		{
			get;
			set;
		}

		/// <summary>
		/// Poll distribute a task
		/// </summary>
		public virtual Poll Poll
		{
			get;
			set;
		}

		public virtual Project Project
		{
			get;
			set;
		}

	}
}

