//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interactions
{
	using Logging;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPoll  : IInteraction
	{
		int MaxVoteCountPerUser { get;set; }

		IEnumerable<IOption> IOption { get;set; }

		IEnumerable<IVote> IVote { get;set; }

		void Vote(IUser pUser, IOption pOption);

	}
}

