//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interactions
{
	using Logging;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface ITask  : IInteraction
	{
		DateTime DueDateTime { get;set; }

		decimal Budget { get;set; }

		long Duration { get;set; }

		long EffectiveDuration { get;set; }

		decimal EffectiveCosts { get;set; }

	}
}

