//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Interactions
{
	using Logging;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Poll : IPoll
	{
		public virtual IInteraction Create()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Delete(IInteraction pInteraction)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Complete(IInteraction pInteraction)
		{
			throw new System.NotImplementedException();
		}

		public virtual void ChangeOwner(IUser pUser)
		{
			throw new System.NotImplementedException();
		}

		public virtual void ChangeIsActive(bool pActive)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Vote(IUser pVote, IOption pOption)
		{
			throw new System.NotImplementedException();
		}

	}
}

