//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Project
{
	public virtual IEnumerable<Poll> Poll
	{
		get;
		set;
	}

	public virtual IEnumerable<User> User
	{
		get;
		set;
	}

	public virtual IEnumerable<Task> Task
	{
		get;
		set;
	}

	public virtual Account Account
	{
		get;
		set;
	}

}

