//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Task
{
	public virtual IEnumerable<Expense> Expense
	{
		get;
		set;
	}

	public virtual Task Task
	{
		get;
		set;
	}

	public virtual IEnumerable<Task> Task
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

	public virtual Project Project
	{
		get;
		set;
	}

}

