//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User : Interface3
{
	public virtual long ID
	{
		get;
		set;
	}

	public virtual string UserName
	{
		get;
		set;
	}

	public virtual string FirstName
	{
		get;
		set;
	}

	public virtual string LastName
	{
		get;
		set;
	}

	public virtual string MiddleName
	{
		get;
		set;
	}

	private string Password
	{
		get;
		set;
	}

	public event object LoggedIn;

	public event object LoggedOut;

	public virtual IEnumerable<Poll> Poll
	{
		get;
		set;
	}

	public virtual IEnumerable<Vote> Vote
	{
		get;
		set;
	}

	public virtual IEnumerable<Task> Task
	{
		get;
		set;
	}

	public virtual LogInEventHandler Class1
	{
		get;
		set;
	}

	public virtual IEnumerable<Project> Project
	{
		get;
		set;
	}

	public virtual void LogIn(string pUserName, string pPassword)
	{
		throw new System.NotImplementedException();
	}

	public virtual void LogOut()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Invite(string pEmailAddress)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Invite(User pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Block(User pUser)
	{
		throw new System.NotImplementedException();
	}

}

