//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Vote
{
	public virtual User User
	{
		get;
		set;
	}

	public virtual Poll Poll
	{
		get;
		set;
	}

	public virtual Option Option
	{
		get;
		set;
	}

}

