//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PlexByte.MoCap.Security
{
	using PlexByte.MoCap.Logging;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPerson 
	{
		string FirstName { get;set; }

		string LastName { get;set; }

		string MiddleName { get;set; }

		string EmailAddress { get;set; }

	}
}

