//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PlexByte.MoCap.Security
{
	using PlexByte.MoCap.Logging;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IUser  : IPerson
	{
		string UserName { get;set; }

		string Id { get;set; }

		void LogIn();

		void LogOut();

	}
}

