//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PlexByte.MoCap.Security
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class User : IUser
	{
		public virtual void LogIn()
		{
			throw new System.NotImplementedException();
		}

		public virtual void LogOut()
		{
			throw new System.NotImplementedException();
		}

	}
}

