//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PlexByte.MoCap.Interactions
{
	using PlexByte.MoCap.Logging;
	using PlexByte.MoCap.Security;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Accounting : IAccounting
	{
		public virtual IInteraction Create(string pText)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Delete(IInteraction pInteraction)
		{
			throw new System.NotImplementedException();
		}

		public virtual void OnComplete(IInteraction pInteraction, InteractionEventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public virtual void ChangeOwner(IUser pUser)
		{
			throw new System.NotImplementedException();
		}

		public virtual void ChangeIsActive(bool pActive)
		{
			throw new System.NotImplementedException();
		}

		public virtual void AttachBill()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Edit()
		{
			throw new System.NotImplementedException();
		}

	}
}

