//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PlexByte.MoCap.Interactions
{
	using PlexByte.MoCap.Security;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum InteractionType
	{
		Poll,
		Task,
		Project,
	}
}
