//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PlexByte.MoCap.Interactions
{
	using PlexByte.MoCap.Logging;
	using PlexByte.MoCap.Security;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IPoll  : IInteraction
	{
		int MaxVoteCountPerUser { get;set; }

		IEnumerable<IOption> IOption { get;set; }

		IEnumerable<IVote> IVote { get;set; }

		ITask ITask { get;set; }

		void Vote(IVote pVote);

		IOption AddOption(string pText);

		IVote AddVote(IOption pOption, IUser pUser);

	}
}

