//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PlexByte.MoCap.Interactions
{
	using PlexByte.MoCap.Logging;
	using PlexByte.MoCap.Security;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IProject  : IInteraction
	{
		bool EnablePoll { get;set; }

		bool EnableBalance { get;set; }

		List<string> InvitationList { get;set; }

		void AddTask(ITask pTask);

		void AddPoll(IPoll pPoll);

		void Invite(IUser pUser);

		void AcceptInvitation();

		void KickUser(IUser pUser);

		void Leave();

	}
}

