//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PlexByte.MoCap.Interactions
{
	using PlexByte.MoCap.Logging;
	using PlexByte.MoCap.Security;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface ITask  : IInteraction
	{
		DateTime DueDateTime { get;set; }

		decimal Budget { get;set; }

		long Duration { get;set; }

		long EffectiveDuration { get;set; }

		decimal EffectiveCosts { get;set; }

		void UpdateProgress(int pProgress);

		void OnBudgetExceeded(ITask pTask, InteractionEventArgs e);

		void AddExpense(IExpense pExpense);

		void AddTimeSlice(ITimeSlice pTimeSlice);

	}
}

