//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;


public class Expense : IExpense, IInteraction
{

    #region Properties

    public decimal Value { get; set; }
    public Image Receipt { get; set; }
    public IInteraction Target { get; set; }
    public string TaskId { get; set; }
    public string Id { get; set; }
    public DateTime StartDateTime { get; set; }
    public DateTime EndDateTime { get; set; }
    public DateTime CreatedDateTime { get; set; }
    public DateTime ModifiedDateTime { get; set; }
    public bool IsActive { get; set; }
    public string Text { get; set; }
    public InteractionType Type { get; set; }
    public IUser Creator { get; set; }
    public IUser Owner { get; set; }
    public InteractionState State { get; set; }
    List<Image> ImageList { get; set; }
    List<decimal> ValueList { get; set; }

    #endregion

    #region Variables

    private IUser _owner;
    private IUser _creator;
    private DateTime _modifiedDateTime;
    private DateTime _createdDateTime;
    private System.Timers.Timer _stateTimer = new System.Timers.Timer(60 * 1000);
    private InteractionState _state;
    private bool _isActive;
    private string _id;

    #endregion

    #region Events

    public event Complete Completed;
    public event Modify Modified;
    public event StateChange StateChanged;

    #endregion

    #region Ctor & Dtor

    /// <summary>
    /// Constructor of the class
    /// </summary>
    /// <param name="pId"></param>
    /// <param name="pText"></param>
    /// <param name="pCreator"></param>
    public Expense(string pId, string pText, IUser pCreator)
    {
        List<Image> pImageList = new List<Image>();
        List<decimal> pValueList = new List<decimal>();
        InitializeProperties(pId, pText, pImageList, pValueList, pCreator);
    }

    /// <summary>
    /// Constructor of the class
    /// </summary>
    /// <param name="pId"></param>
    /// <param name="pText"></param>
    /// <param name="pImageList"></param>
    /// <param name="pCreator"></param>
    public Expense(string pId, string pText, List<Image> pImageList, List<decimal> pValueList, IUser pCreator)
    {
        InitializeProperties(pId, pText, pImageList, pValueList, pCreator);
    }

    #endregion

    #region Event raising methods

    /// <summary>
    /// This method raises the corresponding event in case subscribers are registered
    /// </summary>
    /// <param name="pEventArgs"></param>
    public virtual void OnComplete(InteractionEventArgs pEventArgs)
    {
        Completed?.Invoke(this, pEventArgs);
    }

    /// <summary>
    /// This method raises the corresponding event in case subscribers are registered
    /// </summary>
    /// <param name="pEventArgs"></param>
    public virtual void OnModify(InteractionEventArgs pEventArgs)
    {
        Modified?.Invoke(this, pEventArgs);
    }

    /// <summary>
    /// This method raises the corresponding event in case subscribers are registered
    /// </summary>
    /// <param name="pEventArgs"></param>
    public virtual void OnStateChanged(InteractionEventArgs pEventArgs)
    {
        StateChanged?.Invoke(this, pEventArgs);
    }

    #endregion

    #region Public methods

    /// <summary>
    /// This method changes the owner of the expense and raises the modified event if the owner is different
    /// used to create a secound project-admin
    /// </summary>
    /// <param name="pUser"></param>
	public virtual void ChangeOwner(IUser pUser)
    {
        if (_owner != pUser)
        {
            _owner = pUser;
            List<InteractionAttributes> changedAttributes = new List<InteractionAttributes>();
            changedAttributes.Add(InteractionAttributes.Owner);
            OnModify(new InteractionEventArgs($"Survey owner changed [Id={Id}]", DateTime.Now, InteractionType.Expense));
        }
    }

    /// <summary>
    /// This method changes the active flag of the object. This can occure if the item expired, finished or was 
    /// cancelled. It will raise the Modified event once changed
    /// </summary>
    /// <param name="pActive"></param>
	public virtual void ChangeIsActive(bool pActive)
    {
        if (_isActive != pActive)
        {
            _isActive = pActive;
            List<InteractionAttributes> changedAttributes = new List<InteractionAttributes>();
            changedAttributes.Add(InteractionAttributes.IsActive);
            OnModify(new InteractionEventArgs($"Survey IsActive changed [Id={Id}]", DateTime.Now, InteractionType.Expense));
        }
    }


    /// <summary>
    /// Adds a "Receipt" to the receiptlist
    /// </summary>
    /// <param name="pImage"></param>
    public virtual void AddReceipt(Image pImage, decimal pValue)
    {
        ValueList.Add(pValue);
        List<InteractionAttributes> changedAttributes = new List<InteractionAttributes>();
        changedAttributes.Add(InteractionAttributes.ValueList);
        if (pImage != null)
        {
            ImageList.Add(pImage);
            changedAttributes.Add(InteractionAttributes.ImageList);
        }
        OnModify(new InteractionEventArgs($"Survey IsActive changed [Id={Id}]", DateTime.Now, InteractionType.Expense));
        ExpenseValue();
    }

    /// <summary>
    /// To edit the receipt, the old one is removed and a new is being created
    /// </summary>
    /// <param name="pImage"></param>
    /// <param name="pNewImage"></param>
    public virtual void EditReceipt(Image pImage, Image pNewImage, decimal pValue, decimal pNewValue)
    {
        if (ImageList.Contains(pImage))
        {
            if (pImage != pNewImage && pValue != pNewValue)
            {
                List<InteractionAttributes> changedAttributes = new List<InteractionAttributes>();
                if (pImage != pNewImage)
                {
                    ImageList.Remove(pImage);
                    ImageList.Add(pNewImage);
                    changedAttributes.Add(InteractionAttributes.ImageList);
                }
                if (pValue != pNewValue)
                {
                    ValueList.Remove(pValue);
                    ValueList.Add(pNewValue);
                    changedAttributes.Add(InteractionAttributes.ValueList);
                    ExpenseValue();
                }
                OnModify(new InteractionEventArgs($"Survey user list changed [Id={Id}]", DateTime.Now, InteractionType.Expense));
            }
        }
    }

    /// <summary>
    /// Deletes a "Receipt" object if it exists in the receiptlist
    /// </summary>
    /// <param name="pImage"></param>
	public virtual void DeleteReceipt(Image pImage, decimal pValue)
    {
        if (ImageList.Contains(pImage))
        {
            ImageList.Remove(pImage);
            ValueList.Remove(pValue);
            List<InteractionAttributes> changedAttributes = new List<InteractionAttributes>();
            changedAttributes.Add(InteractionAttributes.ImageList);
            changedAttributes.Add(InteractionAttributes.ValueList);
            OnModify(new InteractionEventArgs($"Survey user list changed [Id={Id}]", DateTime.Now, InteractionType.Expense));
            ExpenseValue();
        }
    }

    /// <summary>
    /// Changes the state of this interaction and thus causes the stateCHanged event to be fired
    /// </summary>
    /// <param name="pState"></param>
	public virtual void ChangeState(InteractionState pState)
    {
        this._state = pState;
        if (_state == InteractionState.Finished ||
            _state == InteractionState.Cancelled ||
            _state == InteractionState.Expired)
            ChangeIsActive(false);
        List<InteractionAttributes> changedAttributes = new List<InteractionAttributes>();
        changedAttributes.Add(InteractionAttributes.State);
        OnStateChanged(new InteractionEventArgs($"Survey state changed [Id={Id}]", DateTime.Now, InteractionType.Expense));
    }

    #endregion

    #region Private methods

    /// <summary>
    /// Initializes all attributes and started the state timer, which validates the interaction's state every 60
    /// </summary>
    /// <param name="pId"></param>
    /// <param name="pText"></param>
    /// <param name="pImageList"></param>
    /// <param name="pCreator"></param>
    private void InitializeProperties(string pId, string pText, List<Image> pImageList, List<decimal> pValueList, IUser pCreator)
    {
        _id = pId;
        _creator = pCreator;
        Text = pText;
        ImageList = pImageList;
        ValueList = pValueList;
        _createdDateTime = DateTime.Now;
        _modifiedDateTime = DateTime.Now;
        StartDateTime = DateTime.Now;
        EndDateTime = default(DateTime);
        _isActive = true;
        Type = InteractionType.Project;
        _state = StartDateTime <= DateTime.Now ? InteractionState.Active : InteractionState.Queued;
        _stateTimer.Elapsed += OnTimerElapsed;
        _stateTimer.AutoReset = false;
        _stateTimer.Start();
        ExpenseValue();
    }

    private void ExpenseValue()
    {
        foreach(decimal value in ValueList)
        {
            Value =+ value;
        }
    }

    /// <summary>
    /// This method validates the object state and chages if required. Once the interaction is either 
    /// cancelled, finished or expired the state check will suspend
    /// </summary>
    /// <param name="sender">The object calling this method (timer)</param>
    /// <param name="e">The event parameters passed</param>
    private void OnTimerElapsed(object sender, System.Timers.ElapsedEventArgs e)
    {
        if (_state == InteractionState.Active || _state == InteractionState.Queued)
        {
            // Behind schedule?
            if (EndDateTime <= DateTime.Now)
                ChangeState(InteractionState.Behind);
            // Turns active?
            if (StartDateTime <= DateTime.Now && _state == InteractionState.Queued)
                ChangeState(InteractionState.Active);
            // Finished if project is closed?
            if (IsActive == false)
                ChangeState(InteractionState.Finished);
        }

        // Still active?
        if (_state == InteractionState.Active || _state == InteractionState.Queued)
            _stateTimer.Start();
    }

    

    #endregion
}

