//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public static class Helper
{
	public static string GenerateId()
	{
	    return DateTime.Now.ToString("yyyyMMDDHHmmssfff");
	}

    public static int DiffSeconds(DateTime pStartDateTime, DateTime pEndDateTime)
    {
        TimeSpan diff = pEndDateTime - pStartDateTime;
        return Convert.ToInt32(diff.TotalSeconds);
    }

	public static int DiffMinutes(DateTime pStartDateTime, DateTime pEndDateTime)
	{
        TimeSpan diff = pEndDateTime - pStartDateTime;
        return Convert.ToInt32(diff.TotalMinutes);
    }

	public static int DiffHours(DateTime pStartDateTime, DateTime pEndDateTime)
	{
        TimeSpan diff = pEndDateTime - pStartDateTime;
        return Convert.ToInt32(diff.TotalHours);
    }

	public static int DiffDays(DateTime pStartDateTime, DateTime pEndDateTime)
	{
        TimeSpan diff = pEndDateTime - pStartDateTime;
        return Convert.ToInt32(diff.TotalDays);
    }

    //TODO: Implement CalculateAvailableMinutes
    public static int CalculateAvailableMinutes(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

    //TODO: Implement GetTasksByUser
    public static List<ITasks> GetTasksByUser(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

    //TODO: Implement GetPendingSurveysByUser
    public static List<ISurvey> GetPendingSurveysByUser(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

    //TODO: Implement GetProjectsByUser
    public static List<IProject> GetProjectsByUser(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

}

