//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static System.Net.Mime.MediaTypeNames;

public interface IExpense 
{
	decimal Value { get;set; }

	Image Receipt { get;set; }

	void AddReceipt(Image pImage);

	void DeleteReceipt(Image pImage);

	void EditReceipt(Image pImage);

}

