//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

public interface IExpense
{
    decimal Value { get; set; }

    Image Receipt { get; set; }

    IInteraction Target { get; set; }

    string TaskId { get; set; }

    void AddReceipt(Image pImage, decimal pValue);

    void DeleteReceipt(Image pImage, decimal pValue);

    void EditReceipt(Image pImage, Image pNewImage, decimal pValue, decimal pNewValue);

}

