//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public delegate void Complete(object sender, InteractionEventArgs e);
public delegate void Modify(object sender, InteractionEventArgs e);

public interface IInteraction
{
    event Complete Completed;
    event Modify Modified;

    string Id { get; }

    DateTime StartDateTime { get; set; }

    DateTime EndDateTime { get; set; }

    DateTime CreatedDateTime { get; }

    DateTime ModifiedDateTime { get; }

    bool IsActive { get; }

    string Text { get; set; }

    InteractionType Type { get; set; }

    IUser Creator { get; }

    IUser Owner { get; }

    InteractionState State { get; set; }

    void OnComplete(InteractionEventArgs pEventArgs);

    void ChangeOwner(IUser pUser);

    void ChangeIsActive(bool pActive);

    void OnModify(InteractionEventArgs pEventArgs);
}

