//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InteractionEventArgs
{
	public virtual InteractionType Type
	{
		get;
		set;
	}

	public virtual DateTime EventDateTime
	{
		get;
		set;
	}

	public virtual string Message
	{
		get;
		set;
	}

    public virtual List<InteractionAttributes> ChangedAttributeList { get; set; }

    public InteractionEventArgs(string pMessage, DateTime pEventDateTime, InteractionType pType) :
        this(pMessage, pEventDateTime, pType, new List<InteractionAttributes>()) { }

    public InteractionEventArgs(string pMessage, DateTime pEventDateTime, InteractionType pType, 
        List<InteractionAttributes> pChangedAttributes)
    {
        this.Type = pType;
        EventDateTime = pEventDateTime;
        Message = pMessage;
        ChangedAttributeList = pChangedAttributes;
    }
}

