//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IProject 
{
    //events



    bool EnableBalance { get; set; }

    bool EnableSurvey { get; set; }

    List<IUser> InvitationList { get; set; }

    IAccount ProjectAccount { get; set; }

    List<ITask> TaskList { get; set; }

    List<ISurvey> SurveyList { get; set; }

    List<IUser> MemberList { get; set; }

    void AddTask(ITask pTask);

    void AddSurvey(ISurvey pSurvey);

    void Invite(IUser pUser);

    void Accept(IUser pUser);

    void Leave();

    void KickUser(IUser pUser);

}

