//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class TaskFactory : ITaskFactory
{
	public virtual void Add(ITimeslice pTimeslice, ITask pTask)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Add(IExpense pExpense, ITask pTask)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Assign(IUser pUser)
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateProgress(int pProgress)
	{
		throw new System.NotImplementedException();
	}

	public virtual ITask CreateTask(string pId, string pText, IUser pCreator)
	{
		throw new System.NotImplementedException();
	}

	public virtual ITask CreateTask(string pId, string pText, IUser pCreator, DateTime pStartDT, DateTime pEndDT, DateTime pDueDT)
	{
		throw new System.NotImplementedException();
	}

	public virtual ITask CreateTask(string pId, string pText, IUser pCreator, DateTime pStartDT, DateTime pEndDT, DateTime pDueDT, decimal pBudget, int pDuration, int pPriority, InteractionState pState, List<IExpense> pExpenses, List<ITimeslice> pTime, List<ITask> pSubTask, int pProgress = 0)
	{
		throw new System.NotImplementedException();
	}

}

