//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logging
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface ITraceService 
	{
		bool CompressFile { get;set; }

		object Log { get;set; }

		void OnDayRolledOver(object sender, EventArgs e);

		void OnSizeRolledOver(object sender, EventArgs e);

		void GetTargetInstance();

		void CompressLogFile(CompressionLevel level, string pTargetPath);

	}
}

