//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Logging
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Trace : ITraceService
	{
		public virtual void OnDayRolledOver(object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public virtual void OnSizeRolledOver(object sender, EventArgs e)
		{
			throw new System.NotImplementedException();
		}

		public virtual ITraceTarget GetTargetInstance()
		{
			throw new System.NotImplementedException();
		}

		public virtual void CompressLogFile(CompressionLevel level, string pTargetPath)
		{
			throw new System.NotImplementedException();
		}

	}
}

